### PR TITLE
Support unordered lists

### PR DESCRIPTION
**Pull request by ceddlyburge**
This is taken from the github-action branch, as master was failing when I forked.

This pull request adds support for unordered lists (which can be nested) in a similar but not identical way to markdown.

One interesting thing is that `get_block` trims whitespace from the end of the string, so we either have to match any '-' at the beginning of a line, or stop trimming whitespace, or disallow a blank final list item. I have gone with the last option for now. Maybe it is possible to get complicated and only match a dash without a following space for the final item.

At the moment the unordered lists are written out using spaces to indent the bullet points, and no change in bullet point for each level of nesting. This may or may not be the best thing, but I think it would be good to get a few more use cases before making a decision.

### CODE REVIEW

**Comment by mpizenberg** [comment]
I've rebased this on the latest master. I hope I haven't introduced any behavior change while resolving merge conflicts (I don't think so). Thanks for this work! I'll try to review this asap :)

**Comment by mpizenberg** [comment]
This PR is quite big, and it spans the whole project, including parsing and layout. I have no idea how the layout is done so I'll review the parsing part first and then I'll ask @Meight his opinion on the layout part.

The success parser tests seem to have been setup differently than previously. Although the usage of `test_case` makes it easier to write tests densely with parameters, it seems to me that we could just as easily reuse the associated function in a few tests. That would avoid bringing the `test_case` dependency.
Also, those unordered list tests are all run on inlined string slices, while the other tests are run on files written to disk in an asset directory. I agree that such unit tests with string slices are useful. Let's go for it and as suggested in one of your comments, import and use `parse_unordered_list` or `parse_content` directly.

In the tests written I see that every-time there is a linux and windows version. Being thorough is important but there are only very few ways for your parser to work on one and not on the other. So in my opinion, it would be better to have just one test to check that both linux and windows end of lines are dealt with correctly. (By the way, you reversed the "linux" and "windows" cases in your comments, it windows that uses a carriage return `\r\n`). Then we can write the other unit tests with multiline string literals to make them much clearer.

In your tests, I see a few `assert!(p.is_ok())` followed by `p.unwrap()`. It's fine to just do things like `let (_, content) = parse_content(dex).unwrap();` directly in tests. If it fails, it will just fail the test which is fine as it's what we want. In general trying to make tests as clear as possible is a good thing.

I changed some tests to reflect some of the comments above. Don't hesitate to make the changes on the other tests, or wait until I finish my review of the whole PR if you prefer.

**Comment by ceddlyburge** [comment]
Hi Matthieu, I've made those changes.

I haven't retrospectively changed the existing tests to use parse_content or similar instead of reading files on disk, but I'm happy to do this if you want.

Cheers, Cedd

**Comment by mpizenberg** [comment]
I hope you’re not too annoyed at me having never finished this review ...  I’m probably not going to finish it, but anyway your rust knowledge has certainly evolved since this was open, and we are very likely going to archive the spandex repo as https://github.com/typst/typst is much more advanced and now open source. BTW don’t hesitate to have a look at it, its quite amazing and almost the perfect execution of what we had envisioned for spandex anyway ^^.

**Pull request closed without merging**
